#!/usr/bin/env node
/**
 * Precompile landing/*.jsx → landing/bundle.js
 * Run from repo root:
 *   node scripts/build-landing.js
 *
 * Produces a single IIFE-wrapped plain-JS file with all landing components.
 * No Babel needed in the browser.
 */

const fs = require('node:fs');
const path = require('node:path');
const babel = require('@babel/core');

// ORDER MATTERS — later files depend on earlier ones via window globals.
const SOURCES = [
  'data.jsx',
  'logo.jsx',
  'hero.jsx',
  'sections.jsx',
  'footer-faq.jsx',
  'app.jsx',        // bootstrap must be last
];

const srcDir  = path.join(__dirname, '..', 'landing');
const outFile = path.join(srcDir, 'bundle.js');

let combined = '/* Yuntona landing — precompiled bundle.\n';
combined += ' * Generated by scripts/build-landing.js from landing/*.jsx.\n';
combined += ' * DO NOT EDIT DIRECTLY — re-run the build script instead.\n';
combined += ' */\n';
combined += '(function () {\n"use strict";\n';

for (const file of SOURCES) {
  const srcPath = path.join(srcDir, file);
  if (!fs.existsSync(srcPath)) {
    console.error(`[build-landing] missing ${file} — aborting`);
    process.exit(1);
  }
  const src = fs.readFileSync(srcPath, 'utf8');
  const { code } = babel.transformSync(src, {
    presets: [['@babel/preset-react', { runtime: 'classic' }]],
    filename: file,
    babelrc: false,
    configFile: false,
  });
  combined += `\n/* ──────── ${file} ──────── */\n${code}\n`;
}

combined += '\n})();\n';

fs.writeFileSync(outFile, combined);
const kb = (combined.length / 1024).toFixed(1);
console.log(`[build-landing] wrote ${outFile} (${kb} KB, ${SOURCES.length} sources)`);
